# syntax=docker/dockerfile:1
# build edumeet 
FROM node:16-bullseye-slim AS edumeet-builder

# Args
ARG BASEDIR
ARG EDUMEETCLIENT
ARG NODE_ENV
ARG SERVER_DEBUG
ARG GIT_SERVER
ARG REPOSITORY
ARG BRANCHCLIENT
ARG REACT_APP_DEBUG

WORKDIR ${BASEDIR}

RUN apt-get update;DEBIAN_FRONTEND=noninteractive apt-get install -yq git bash jq build-essential python python3-pip openssl libssl-dev pkg-config;apt-get clean

#checkout code
RUN git clone --single-branch --branch ${BRANCHCLIENT} ${GIT_SERVER}/${REPOSITORY}/${EDUMEETCLIENT}.git

#install app dep
WORKDIR ${BASEDIR}/${EDUMEETCLIENT}
RUN yarn install --production=false; yarn build

#set and build app in producion mode/minified/.
#RUN ["/bin/bash", "-c", "cat <<< $(jq '.bundleDependencies += .dependencies' package.json) > package.json" ]
#RUN 

# create edumeet-client image
FROM nginx
WORKDIR /usr/share/nginx/html/
COPY --from=edumeet-builder /opt/edumeet-client/build/  /usr/share/nginx/html/

# Web PORTS
EXPOSE 80
EXPOSE 443
