FROM node:18-bullseye-slim

ARG EDUMEET_SERVER
ARG GIT_SERVER
ARG REPOSITORY
ARG BRANCH_SERVER

WORKDIR /app

#install server build dependency
RUN apt-get update;DEBIAN_FRONTEND=noninteractive apt-get install -yq git bash jq build-essential python python3-pip openssl pkg-config;apt-get clean

#checkout code
RUN git clone --single-branch --branch ${BRANCH_SERVER} ${GIT_SERVER}/${REPOSITORY}/${EDUMEET_SERVER}.git

WORKDIR /app/${EDUMEET_SERVER}

COPY  certs/ /app/${EDUMEET_SERVER}/certs
COPY  configs/server/config.json /app/${EDUMEET_SERVER}/config/config.json

RUN mv  /app/${EDUMEET_SERVER}/ /usr/src/app/

WORKDIR /usr/src/app

RUN yarn install
RUN yarn run build

EXPOSE 8443

ARG SERVER_DEBUG

ENTRYPOINT DEBUG=${SERVER_DEBUG} yarn run prodstart $0 $@
