FROM node:18-bullseye-slim
#install server build dependency
RUN apt-get update;DEBIAN_FRONTEND=noninteractive apt-get install -yq git bash jq build-essential python python3-pip openssl pkg-config;apt-get clean

ARG EDUMEET_MGMT_CLIENT
ARG MGMT_CLI_URL
ARG GIT_SERVER
ARG REPOSITORY
ARG BRANCH_MGMT_CLIENT

WORKDIR /app

#checkout code
RUN git clone --single-branch --branch ${BRANCH_MGMT_CLIENT} ${GIT_SERVER}/${REPOSITORY}/${EDUMEET_MGMT_CLIENT}.git

WORKDIR /app/${EDUMEET_MGMT_CLIENT}

RUN mv  /app/${EDUMEET_MGMT_CLIENT} /usr/src/app/

WORKDIR /usr/src/app

RUN yarn
# wont work here because the db is not yet running 
#RUN npm run migrate # Run migrations to set up the database
ARG MGMT_CLIENT_DEBUG
ENTRYPOINT DEBUG=${MGMT_CLIENT_DEBUG} MGMT_CLI_URL=${MGMT_CLI_URL} yarn start $0 $@
