FROM node:20-bookworm-slim AS edumeet-cli-builder


#install server build dependency
RUN apt-get update;DEBIAN_FRONTEND=noninteractive apt-get install -yq git bash gettext-base;apt-get clean

ARG EDUMEET_MGMT_CLIENT
ARG MGMT_CLI_URL
ARG GIT_SERVER
ARG REPOSITORY
ARG BRANCH_MGMT_CLIENT

WORKDIR /app

#checkout code
RUN git clone --single-branch --branch ${BRANCH_MGMT_CLIENT} ${GIT_SERVER}/${REPOSITORY}/${EDUMEET_MGMT_CLIENT}.git

WORKDIR /app/${EDUMEET_MGMT_CLIENT}

RUN mv  /app/${EDUMEET_MGMT_CLIENT} /usr/src/app/

WORKDIR /usr/src/app
RUN yarn install --frozen-lockfile
RUN NODE_ENV=production yarn run build
FROM steebchen/nginx-spa:stable
ARG EDUMEET_CLIENT
COPY --from=edumeet-cli-builder /usr/src/app/build/   /app
EXPOSE 80
CMD ["nginx"]


