FROM node:20-bookworm-slim

#install server build dependency
RUN apt-get update;DEBIAN_FRONTEND=noninteractive apt-get install -yq git bash python3 python3-pip gettext-base;apt-get clean

ARG EDUMEET_SERVER
ARG GIT_SERVER
ARG REPOSITORY
ARG BRANCH_SERVER

WORKDIR /app

#checkout code
RUN git clone --single-branch --branch ${BRANCH_SERVER} ${GIT_SERVER}/${REPOSITORY}/${EDUMEET_SERVER}.git

WORKDIR /app/${EDUMEET_SERVER}

#COPY  configs/server/config.json /app/${EDUMEET_SERVER}/config/config.json

RUN mv  /app/${EDUMEET_SERVER}/ /usr/src/app/

WORKDIR /usr/src/app

COPY docker-entrypoint.sh /entrypoint.sh

RUN yarn install --frozen-lockfile --network-concurrency 1 --network-timeout 1000000
RUN yarn run build

EXPOSE 8443

ENTRYPOINT [ "/entrypoint.sh" ]
