FROM node:18-bullseye-slim AS edumeet-builder

# Args
ARG EDUMEET_CLIENT
ARG GIT_SERVER
ARG REPOSITORY
ARG BRANCH_CLIENT

WORKDIR /app

RUN apt-get update;DEBIAN_FRONTEND=noninteractive apt-get install -yq git bash jq build-essential python python3-pip openssl pkg-config;apt-get clean
#checkout code
RUN git clone --single-branch --branch ${BRANCH_CLIENT} ${GIT_SERVER}/${REPOSITORY}/${EDUMEET_CLIENT}.git
WORKDIR /app/${EDUMEET_CLIENT}
COPY  configs/app/config.js /app/${EDUMEET_CLIENT}/public/config/config.js

RUN yarn install --frozen-lockfile
RUN yarn add eslint-config-react-app@v6 -D
RUN yarn run build

# create edumeet-client image
FROM nginx:stable-alpine
WORKDIR /usr/share/nginx/html/
ARG EDUMEET_CLIENT
COPY --from=edumeet-builder /app/${EDUMEET_CLIENT}/build/   /usr/share/nginx/html/

# Web PORTS
EXPOSE 80
EXPOSE 443
EXPOSE 8000
