FROM node:20-bookworm-slim

#install server build dependency
RUN apt-get update;DEBIAN_FRONTEND=noninteractive apt-get install -yq git bash gettext-base;apt-get clean

ARG EDUMEET_SERVER
ARG GIT_SERVER
ARG REPOSITORY
ARG BRANCH_SERVER

WORKDIR /app
RUN useradd -m edumeet
RUN chown -R edumeet:edumeet /app
RUN mkdir -p /usr/src/app 
RUN chown -R edumeet:edumeet /usr/src/app

USER edumeet
#checkout code
RUN git clone --single-branch --branch ${BRANCH_SERVER} ${GIT_SERVER}/${REPOSITORY}/${EDUMEET_SERVER}.git

WORKDIR /app/${EDUMEET_SERVER}

RUN mv  ./* /usr/src/app/

WORKDIR /usr/src/app

COPY docker-entrypoint.sh /entrypoint.sh

RUN yarn install --frozen-lockfile
RUN yarn run build

EXPOSE 8443

ENTRYPOINT [ "/entrypoint.sh" ]
