FROM node:24-bookworm-slim AS edumeet-builder

#install server build dependency
RUN apt-get update;DEBIAN_FRONTEND=noninteractive apt-get install -yq git bash gettext-base;apt-get clean

# Args
ARG EDUMEET_CLIENT
ARG GIT_SERVER
ARG REPOSITORY
ARG BRANCH_CLIENT

WORKDIR /app

#checkout code
RUN git clone --single-branch --branch ${BRANCH_CLIENT} ${GIT_SERVER}/${REPOSITORY}/${EDUMEET_CLIENT}.git
WORKDIR /app/${EDUMEET_CLIENT}
RUN yarn install --frozen-lockfile
RUN NODE_ENV=production yarn run build

#FROM n7remus/nginx-spa:latest
FROM nginx:1.29-alpine
ARG EDUMEET_CLIENT
RUN sed -i '1idaemon off;' /etc/nginx/nginx.conf
COPY Dockerfiles/extra/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=edumeet-builder /app/${EDUMEET_CLIENT}/build/ /app
EXPOSE 80
# Switch to the existing non-root nginx user
CMD ["nginx"]
