FROM node:20-bookworm-slim

#install server build dependency
RUN apt-get update;DEBIAN_FRONTEND=noninteractive apt-get install -yq git bash gettext-base;apt-get clean

ARG EDUMEET_MGMT_SERVER
ARG GIT_SERVER
ARG REPOSITORY
ARG BRANCH_MGMT_SERVER
ARG NODE_TLS_REJECT_UNAUTHORIZED

WORKDIR /app

#checkout code
RUN git clone --single-branch --branch ${BRANCH_MGMT_SERVER} ${GIT_SERVER}/${REPOSITORY}/${EDUMEET_MGMT_SERVER}.git

WORKDIR /app/${EDUMEET_MGMT_SERVER}

RUN mv  /app/${EDUMEET_MGMT_SERVER} /usr/src/app/

WORKDIR /usr/src/app
RUN yarn
RUN rm -fr /usr/src/app/test/
#COPY configs/mgmt/default.json /usr/src/app/config
# Compile TypeScript source
RUN yarn compile 

ARG MGMT_DEBUG
# Run migrations to set up the database
ENTRYPOINT yarn migrate && NODE_TLS_REJECT_UNAUTHORIZED=${NODE_TLS_REJECT_UNAUTHORIZED} DEBUG=${MGMT_DEBUG} yarn start $0 $@








