FROM node:20-bookworm-slim

#install server build dependency
RUN apt-get update;DEBIAN_FRONTEND=noninteractive apt-get install -yq git bash gettext-base;apt-get clean

ARG EDUMEET_MN_SERVER
ARG GIT_SERVER
ARG REPOSITORY
ARG BRANCH_MN_SERVER
ARG MEDIA_SECRET
ARG listenPort=3000
ENV LISTEN_PORT=$listenPort

ARG rtcMinPort=40000
ENV RTC_MIN_PORT=$rtcMinPort

ARG rtcMaxPort=40249
ENV RTC_MAX_PORT=$rtcMaxPort
ARG LISTEN_IP
ARG MN_EXTRA_PARAMS

WORKDIR /app
RUN useradd -m edumeet
RUN chown -R edumeet:edumeet /app
RUN mkdir -p /usr/src/app 
RUN chown -R edumeet:edumeet /usr/src/app
USER edumeet
#checkout code
RUN git clone --single-branch --branch ${BRANCH_MN_SERVER} ${GIT_SERVER}/${REPOSITORY}/${EDUMEET_MN_SERVER}.git

WORKDIR /app/${EDUMEET_MN_SERVER}

RUN yarn install --frozen-lockfile
RUN yarn run build
RUN mv  ./* /usr/src/app/
WORKDIR /usr/src/app

EXPOSE ${LISTEN_PORT}
EXPOSE ${RTC_MIN_PORT}-${RTC_MAX_PORT}/udp
EXPOSE ${RTC_MIN_PORT}-${RTC_MAX_PORT}/tcp

ARG MN_DEBUG

ENTRYPOINT DEBUG=${MN_DEBUG} yarn run prodstart $0 $@








